### PR TITLE
Added API endpoints for list, show and create assembly line.

### PR DESCRIPTION
**Pull request by IsmaelMT**
I didn't add the parts regarding creating lines between stations... Just assembly lines are created with stations.
I'm not very sure if creating stations in the create for Assembly lines goes well with the information hiding principle, I would like to hear your opinions.

Thanks!

### CODE REVIEW

**Comment by dcestari** [comment]
About Rails conventions:
- Controllers are named using the plural form of the entity, for example: `User` model and `UsersController`.
- Migrations use the plural form of the entity, which is the table name, for example: `add_first_name_to_users`.

About the `Station` object creation, you are doing it manually but rails has a method to delegate creation of related objects: http://apidock.com/rails/ActiveRecord/NestedAttributes/ClassMethods/accepts_nested_attributes_for

One could argue that this applies information hiding since we are extracting responsibility from the controller and moving it to the AssemblyLine class which, in turn, delegates creation logic to the Station class.

**Comment by IsmaelMT** [comment]
Fixed the convention issues and added the accepts_nested_attributes_for to create stations from assembly lines.

**Comment by IsmaelMT** [comment]
I just uploaded the API endpoints. I'm doing it in this same pull request because it was little work...

I haven't implemented any tests...

**Comment by dcestari** [comment]
Are you versioning the model? You uploaded a `V1::Line` ActiveRecord subclass.

**Comment by IsmaelMT** [comment]
My mistake =)

**Pull request merged**
